name: payora
description: Next-gen wallet for next-gen living
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  collection: ^1.19.1
  dart_mappable: ^4.6.0
  dio: ^5.9.0
  equatable: ^2.0.7
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_form_builder: ^10.1.0
  flutter_localizations:
    sdk: flutter
  form_builder_extra_fields: ^12.1.0
  form_builder_validators: ^11.2.0
  get_it: ^8.2.0
  go_router: ^16.1.0
  google_fonts: ^6.3.0
  intl: ^0.20.2
  logger: ^2.6.1
  meta: ^1.16.0
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.6.0
  dart_mappable_builder: ^4.6.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
  watcher: ^1.1.2

flutter:
  generate: true
  uses-material-design: true
