name: payora
description: Next-gen wallet for next-gen living
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  collection: ^1.19.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_form_builder: ^10.1.0
  flutter_localizations:
    sdk: flutter
  form_builder_extra_fields: ^12.1.0
  form_builder_phone_field: ^3.0.0
  form_builder_validators: ^11.2.0
  go_router: ^16.0.0
  google_fonts: ^6.3.0
  intl: ^0.20.2
  logger: ^2.6.1
  meta: ^1.16.0
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.4.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
